### ISSUE TITLE
为什么回调JsonResponseHandler

### ISSUE THREAD

**Issue by wei6718189** [tsy12321/MyOkHttp#2]
有两个public void onSuccess(int statusCode, JSONObject response)  有什么作用？

**Comment by tsy12321** [comment]
一个是JSONObject 一个是JSONArray。如果你的返回定义是JSONObject就实现JSONObject，如果是JSONArray就实现JSONArray那个

**Comment by wei6718189** [comment]
哦 还有一个问题 
我在你的demo 上 试了一下 修改了了东西 添加header 和修改了url  为什么返回  系统异常  我这边用AsyncHttpClient添加一样的header返回正常信息    是我添加header 方式有问题吗 ？
  private void doPost() {
//        String url = "http://192.168.2.135/myokhttp/post.php";
        String url = "https://citmp.haohushi.me:8443/quhu/accompany/third/getOpenCities";

        Map<String, String> params = new HashMap<>();
//        params.put("name", "tsy");
//        params.put("age", "24");
        params.put("Authorization","bearer 6b310c46-a080-4adf-9515-585e14c7c6fd");
        params.put("Content-Type","application/json");

        mMyOkhttp.post()
                .url(url)
//                .params(params)
                .tag(this)
                .headers(params)
                .enqueue(new JsonResponseHandler() {
                    @Override
                    public void onSuccess(int statusCode, JSONObject response) {
                        Log.d(TAG, "doPost onSuccess JSONObject:" + response);
                    }

                    @Override
                    public void onSuccess(int statusCode, JSONArray response) {
                        Log.d(TAG, "doPost onSuccess JSONArray:" + response);
                    }

                    @Override
                    public void onFailure(int statusCode, String error_msg) {
                        Log.d(TAG, "doPost onFailure:" + error_msg);
                    }
                });

**Comment by tsy12321** [comment]
额 代码有点乱 没看懂

**Comment by wei6718189** [comment]
就是访问接口换成 我这边的  url = "https://citmp.haohushi.me:8443/quhu/accompany/third/getOpenCities";
再添加header header值是 ：
"Authorization","bearer 6b310c46-a080-4adf-9515-585e14c7c6fd"
"Content-Type","application/json"
其他就没有参数了    我这边看了好久 没看出什么问题来   我确定header值 没有没有问题。你那边可以不可以帮看一下

**Comment by tsy12321** [comment]
应该是我这边有bug 我明天看下

**Comment by wei6718189** [comment]
好的 谢谢。

**Comment by tsy12321** [comment]
我加了log拦截器测试了下。header的确已经加进去了。
![image](https://cloud.githubusercontent.com/assets/9690656/21875788/76bdfa60-d8b9-11e6-8009-60c1c511807c.png)
有可能出现的问题是不是缺失header，比如agent？其他的浏览器之类的可能会自动加上，okhttp这个请求如果没加就是没有的.

**Comment by tsy12321** [comment]
log拦截器已经上传 你可以拉下也测试下

**Comment by wei6718189** [comment]
谢谢  。我这边知道什么原因了 是我这边的问题，即使其他参数为空  我这边也要以JSON格式传过去就可以了
